import os
import re

def load_new_df(file_name:str)->dict[str, dict[str, str]]:
    '''
    Grabs every class in a generated ActiveX DF File and stores the progID.
    
    :param file_name: Path to file
    :return: Dictionary containing class name and every new property ID
    :rtype: dict[str, dict[str, str]]
    '''
    dir_dict = {}
    with open(file_name) as file:
        line = ""
        class_name = ""
        class_checking = False
        while(line:=file.readline()):
            words = line.strip().split()
            if len(words) < 1: continue
            if 'class' == words[0].lower():
                class_checking = True
                class_name = words[1]
                print("Found class: ", class_name)
                dir_dict[class_name] = {}
            elif class_checking:
                if "set"==words[0].lower() and re.match("ps.*id" ,words[1].lower()):
                    property_name = words[1]
                    dir_dict[class_name][property_name] = words[3]
                    print(f"Found property {property_name} in {class_name} with id {words[3]}")
                if 'end_class' == words[0].lower():
                    class_checking = False
                    print("End class: ", class_name)
                    
    return dir_dict

def upgrade_files(class_property_dict:dict[str, dict[str, str]], input_dir_path:str, output_dir_path:str, old_version:str, new_version:str):
    '''
    Upgrades every file in a directory given new class properties and outputs it into a new directory
    
    :param class_property_dict: Dictionary of class properies
    :param input_dir_path: Path to old classes
    :param output_dir_path: Directory where new classes will be generated.
    '''

    if input_dir_path == output_dir_path:
        print("ERROR: Input directory and output directory must be different.")
        return
    
    if not os.path.exists(output_dir_path):
        os.makedirs(output_dir_path)
    
    print(class_property_dict)
    for filename in os.listdir(input_dir_path):
        original_file_path = os.path.join(input_dir_path, filename)
        new_file_path = os.path.join(output_dir_path, filename)
        
        with open(original_file_path, 'r') as original_file:
            lines = original_file.readlines()
            class_checking = False
            class_name = ''
            replace_ids = {}
            if len(old_version.strip()) > 0 and len(new_version.strip()) > 0:
                replace_ids[old_version.strip()] = new_version.strip()

            for i in range(len(lines)):
                words = lines[i].strip().split()
                if len(words) < 1: continue
                if 'class' == words[0].lower():
                    class_name = words[1]
                    if not words[1] in class_property_dict:
                        print(lines[i])
                        print("Class deprecated or not generated by dll: ", class_name)
                        continue
                    class_checking = True
                    print("Found class: ", class_name)
                elif class_checking:
                    if "set"==words[0].lower() and re.match("ps.*id" ,words[1].lower()):
                        property_name = words[1]
                        replace_ids[words[3][1:-1]] = class_property_dict[class_name][property_name][1:-1]
                        print(f"Updating {property_name} of {class_name} from {words[3]} to {class_property_dict[class_name][property_name]}")

                        lines[i] = lines[i].replace(words[3], class_property_dict[class_name][property_name])
                    if 'end_class' == words[0].lower():
                        class_checking = False
                        print("End class: ", class_name)
            
            with open(new_file_path, 'w') as new_file:
                for l in lines:
                    for r in replace_ids:
                        l = l.replace(r, replace_ids[r])
                    new_file.write(l)
                






if __name__ == "__main__":

    base_directory = input("DF Base Directory(full path): ")
    new_df = input("New DF Upgrade File: ")
    output_directory_path = input("DF Upgraded Directory: ")
    
    class_properties = load_new_df(new_df)
    version_input = input("Old Version Number(optional): ")
    version_output = input("New Version Number(optional): ")
    upgrade_files(class_properties, base_directory, output_directory_path, version_input, version_output)
    
    pass